name: Deploy terraform in GCP

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate github with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/385244489116/locations/global/workloadIdentityPools/tf-gh-action/providers/github"
          service_account: "terraform-demo@stunning-ruler-469007-u5.iam.gserviceaccount.com"

      - name: gcloud Auth
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
